# This file configures poetry for this particular project. The goal of is to
# avoid any poetry headaches by keeping settings consistent amongst collaborators.
#
# For more information: https://python-poetry.org/docs/configuration

[virtualenvs]
# For local development We do not want Poetry to be responsible for creating
# virtual environments. Instead, use `python -m venv .venv` to create a virtual
# environment in the root directory of the repository. This is where poetry will
# look for the environment.
in-project = true
create = false
