name: Python package

on:
  push:
    branches:
      - main
      - "releases/**"
  pull_request:
    branches:
      - main
      - "releases/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "1.7.1"

      - name: Configure Poetry for CI build
        run: |
          poetry config --unset virtualenvs.create  --local
          poetry config --unset virtualenvs.in-project --local

      - uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ matrix.os }}-${{ matrix.python-version }}-{{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: make install

      - name: Run pre-commit hooks
        uses: pre-commit/action@v3.0.0

      - name: CI
        run: make ci
